language: java
jdk:
- oraclejdk8
before_script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn clean install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=indrabasak-github
  -Dsonar.login=$SONAR_TOKEN
cache:
  directories: "– $HOME/.m2 – $HOME/.sonar/cache"
notifications:
  email:
  - indra.basak1@gmail.com
  on_success: change
  on_failure: always
  use_notice: true
env:
  global:
    secure: gqoRcQ0040FFJtS9ihp7Nv3VWzggnSVsxdbYW5JO79dFqyPKibGT6au/FslA+dsaROnvoPLmkKDf7RNK0Iu03ReHFkD3HOLTHk2E+SUor8YkXLooyBMroTMxmcDAF+vjHpfBtn8xG6D+GT+Gh2IYG3hIFoajrteuUSoVVvt4jF3m9zuYgnRT3hWTV42wyGXvRFYaBhggxi38dwrMzsoFTLWZv8PBFW9u/GSdpeWl2PdH0K44k8BC5/WuPUibsHdf1K0uEpRsU8D5+4DJmNq0wV+zK9/qwoA+/1hABZ5xCmQ6r04pGzdlWrAIZuTCK53e7lyhUjDwxr2HRJICGMqes/JnFT98jHw+/p3rBhi7MzxTdY2bc0j+/BYoSGeMZ12QNhfSgSyNPJW6r7BRs5tJbCm/enhdbxKhi0tPryN01BFgyBe5QjtSgEF04NZH+GTpuaMX8VDmmX63dDUXLclWfy6aiwHg6uX4GK2aeSbMWMk6Lg5ZYphEpHNwaCZubUN1Iea64EKOfpByWHCILv3vzJl3m+bDLZNOFfd8dPAFwnWQHsft9ts0R2dbrN/nYo5NwBcIYmA6IDf7qXeYVtrgZ6Ep5qRkSnKeGlxu88vRFNAv7xN3VvF07yw6Rr6LetvU4dmDJc6nhpt85rZAe/BsfZOcRlaYHHmUHHmIh+SH3ug=
